# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci

  build:
    runs-on: ubuntu-latest

    needs: prepare
    steps:
    - run: npm run build
    - run: npm test

  docs:
    runs-on: ubuntu-latest

    needs: prepare
    steps:
    - run: npm run docs:build
    - uses: EndBug/add-and-commit@v7.0.0
      with:
        add: '-A .'
        message: Update docs
