name: 'Publish @next'

on:
  pull_request:
    branches: [ main ]

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - run: npm ci
    - run: npm run build
    - run: npm run docs:build

    - uses: EndBug/add-and-commit@v7.0.0
      with:
        add: '-A .'
        message: Update docs

    - run: npm test
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions-ecosystem/action-release-label@v1
      id: release

    - uses: martinbeentjes/npm-get-version-action@master
      id: package

    - run: npm run preversion
      if: ${{ contains(steps.package.outputs.current-version, '.rc-') }}

    - run: npm run pre${{ steps.release.outputs.level }}
      if: ${{ !contains(steps.package.outputs.current-version, '.rc-') }}
